# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leader-election-cluster-role
rules:
  - apiGroups:
      - "v1"
    resources:
      - namespace
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
  - apiGroups:
      - "apps/v1"
    resources:
      - deployment
    verbs:
      - list
      - watch
      - patch