name: Package

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/ci.yaml'
      - '.github/workflows/e2e.features.yaml'
      - 'hack/**'
      - 'test/**'
      - '**.md'

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PKG_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PKG_GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      - name: Push to GitHub Packages
        run: |
          docker build -t docker.pkg.github.com/arugal/laborer/manager:latest .
          docker push docker.pkg.github.com/arugal/laborer/manager:latest