name: Image

on:
  push:
    branches:
      - image

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: arugal/laborer/manager
          tag_with_ref: true
