name: E2E

on:
  pull_request:
  push:
    branches:
      - master

env:
  SCRIPTS_DIR: test/scripts

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        case:
          - {name: 'Kubernetes 1.16', tag: 'v1.16.1'}
          - {name: 'Kubernetes 1.17', tag: 'v1.17.1'}
          - {name: 'Kubernetes 1.18', tag: 'v1.18.1'}
          - {name: 'Kubernetes 1.19', tag: 'v1.19.1'}
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Prepare envrionment
        run: bash ${SCRIPTS_DIR}/pre.sh
      - name: Create Kubrnetes With Kind
        run: |
          kind create cluster --image kindest/node:${{ matrix.case.tag }} --wait 60s
          kubectl version
      - name: Build Docker Image
        run: |
          make docker-build
          docker images
          kind load docker-image controller:latest
      - name: Deploy Laborer
        run: |
          kubectl create ns laborer-system
          bash hack/webhook-create-signed-cert.sh --namespace laborer-system --service laborer-webhook-service --secret laborer-webhook-server-cert
          cat config/default/webhook_ca_bundle_patch_template.yaml | bash hack/webhook-patch-ca-bundle.sh > config/default/webhook_ca_bundle_patch.yaml
          export IMG=controller:latest
          make deploy

          sleep 5
          kubectl get all -n laborer-system
          kubectl wait --for=condition=available deployment.apps/$(kubectl get deployment -n laborer-system | awk '$1 !~ /NAME/ {print $1}') -n laborer-system --timeout=60s
          kubectl logs $(kubectl get pods -n laborer-system | awk '$1 !~ /NAME/ {print $1}') -n laborer-system
      - name: Logs
        if: ${{ failure() }}
        run: |
          kubectl get pods -n laborer-system -o yaml
      - name: Clean Up
        if: ${{ always() }}
        run: kind delete cluster

  build-expected:
    name: E2E All
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs: [e2e]
    steps:
      - name: Call me by your name
        run: echo "Birds of a feather flock together"